{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "cobweb.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "32m"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts: ["{{ .Values.ingress.host }}"]
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service: { name: {{ include "cobweb.fullname" . }}-api, port: { name: http } }
          - path: /public
            pathType: Prefix
            backend:
              service: { name: {{ include "cobweb.fullname" . }}-api, port: { name: http } }
          - path: /docs
            pathType: Prefix
            backend:
              service: { name: {{ include "cobweb.fullname" . }}-api, port: { name: http } }
          - path: /openapi.json
            pathType: Exact
            backend:
              service: { name: {{ include "cobweb.fullname" . }}-api, port: { name: http } }
          - path: /
            pathType: Prefix
            backend:
              service: { name: {{ include "cobweb.fullname" . }}-web, port: { name: http } }
{{- end }}
