apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cobweb.fullname" . }}-web
  labels:
    {{- include "cobweb.labels" . | nindent 4 }}
    component: web
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        component: web
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      containers:
        - name: web
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}/web:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports: [{ containerPort: 3000, name: http }]
          resources: {{- toYaml .Values.web.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: { drop: ["ALL"] }
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cobweb.fullname" . }}-web
spec:
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    component: web
  ports:
    - port: 80
      targetPort: http
      name: http
